name: 'nightly-test'
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stable:
    uses: ./.github/workflows/integration-test.yml
    with:
      shell-installer-url: https://autify-cli-assets.s3.amazonaws.com/autify-cli/channels/stable/install-cicd.bash
