# This is a basic workflow to help you get started with Actions

name: shell-checker

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  shell-checker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional if sh_checker_comment is false.
          SHELLCHECK_OPTS: -e SC1004 # Optional: exclude some shellcheck warnings.
          SHFMT_OPTS: -i 2 -ci # Optional: pass arguments to shfmt.
        with:
          sh_checker_comment: true
